// <auto-generated />
namespace WaterDelivery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddPhone2andAAddressToSetting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPhone2andAAddressToSetting));
        
        string IMigrationMetadata.Id
        {
            get { return "202006231804040_AddPhone2andAAddressToSetting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
